version: "3.9"

services:
  database:
    image: postgres
    hostname: database
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    build: .
    links:
      - database
    ports:
      - "8080:8080"
