postgres:
  host: 'localhost:5432'
  dbname: 'mailing'
  schema: 'core'
  user: 'mailing'
  password: 'mailing'

spring:
  liquibase:
    enabled: true

server:
  port: 8081

management:
  server:
    port: 8091
